# Generated by Django 3.0.6 on 2020-05-27 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='nombreCiudad',
            new_name='nombre_Ciudad',
        ),
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='tipoDocumento',
            new_name='tipo_Documento',
        ),
        migrations.AlterField(
            model_name='person',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Ciudad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tipoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.TipoDocumento'),
        ),
    ]
